# Generated by Django 4.0.1 on 2022-02-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-_Tkhr9tZFkGuROsBCsWmJwE7a_MXAEsLfpldSkD1nLb8F8HSKpIXTu55Pv8UZNbnfSY&usqp=CAU', max_length=500),
        ),
    ]
